export * from "./mechanic/MechanicListPage.tsx"
export * from "./mechanic/MechanicPage.tsx"
export * from "./vehicleBrand/VehicleBrandListPage.tsx" 
export * from "./vehicleBrand/VehicleBrandPage.tsx" 
export * from "./typeVehicle/TypeVehicleListPage.tsx" 
export * from "./typeVehicle/TypeVehiclePage.tsx" 
export * from "./taller/TallerListPage.tsx" 
export * from "./taller/TallerPage.tsx" 
export * from "./cliente/ClienteListPage.tsx" 
export * from "./cliente/ClientePage.tsx" 
export * from "./diasNoDisponibles/DiasNoDisponiblesListPage.tsx" 
export * from "./diasNoDisponibles/DiasNoDisponiblesPage.tsx" 
export * from "./vehiculo/VehiculoListPage.tsx" 
export * from "./vehiculo/VehiculoPage.tsx" 
export * from "./nivelGravedad/NivelGravedadListPage.tsx" 
export * from "./nivelGravedad/NivelGravedadPage.tsx" 
export * from "./mechanicalSpecialty/MechanicalSpecialtyListPage.tsx";
export * from "./mechanicalSpecialty/MechanicalSpecialtyPage.tsx";
export * from "./marcaHerramienta/MarcaHerramientaListPage.tsx";
export * from "./marcaHerramienta/MarcaHerramientaPage.tsx";
export * from "./herramientas/HerramientaListPage.tsx";
export * from "./herramientas/HerramientaPage.tsx";
export * from "./cotizacion/CotizacionListPage.tsx";
export * from "./cotizacion/CotizacionPage.tsx";
export * from "./tipoPago/TipoPagoListPage.tsx";
export * from "./tipoPago/TipoPagoPage.tsx";
export * from "./tipoRepuesto/TipoRepuestoListPage.tsx";
export * from "./tipoRepuesto/TipoRepuestoPage.tsx";
export * from "./proveedor/ProveedorListPage.tsx";
export * from "./proveedor/ProveedorPage.tsx";
export * from "./repuesto/RepuestoListPage.tsx";
export * from "./repuesto/RepuestoPage.tsx";
export * from "./marcaProducto/MarcaProductoListaPage.tsx";
export * from "./marcaProducto/MarcaProductoPage.tsx";
export * from "./marcaEquipo/MarcaEquipoListPage.tsx";
export * from "./marcaEquipo/MarcaEquipoPage.tsx";
export * from "./tipoServicio/TipoServicioListPage.tsx";
export * from "./tipoServicio/TipoServicioPage.tsx";
export * from "./cita/CitaListPage.tsx";
export * from "./cita/CitaPage.tsx";
export * from "./producto/ProductoListPage.tsx";
export * from "./producto/ProductoPage.tsx";