export * from "./MechanicListPage.tsx"
export * from "./MechanicPage.tsx"
export * from "./vehicleBrand/VehicleBrandListPage.tsx" 
export * from "./vehicleBrand/VehicleBrandPage.tsx" 
export * from "./typeVehicle/TypeVehicleListPage.tsx" 
export * from "./typeVehicle/TypeVehiclePage.tsx" 
export * from "./taller/TallerListPage.tsx" 
export * from "./taller/TallerPage.tsx" 
export * from "./cliente/ClienteListPage.tsx" 
export * from "./cliente/ClientePage.tsx" 
export * from "./diasNoDisponibles/DiasNoDisponiblesListPage.tsx" 
export * from "./diasNoDisponibles/DiasNoDisponiblesPage.tsx" 
export * from "./vehiculo/VehiculoListPage.tsx" 
export * from "./vehiculo/VehiculoPage.tsx" 
export * from "./nivelGravedad/NivelGravedadListPage.tsx" 
export * from "./nivelGravedad/NivelGravedadPage.tsx" 
export * from "./marcaProducto/MarcaProductoListaPage.tsx";
export * from "./marcaProducto/MarcaProductoPage.tsx";
export * from "./marcaEquipo/MarcaEquipoListPage.tsx";
export * from "./marcaEquipo/MarcaEquipoPage.tsx";